lib/payment_services.rb
lib/payment_services/any_money.rb
lib/payment_services/any_money/client.rb
lib/payment_services/any_money/invoicer.rb
lib/payment_services/any_money/payout.rb
lib/payment_services/any_money/payout_adapter.rb

https://docs.any.money/ru/payout/
Code of migration: https://gist.github.com/m1ndg8mer/aeafe221ff0d65c07720052f35dad562

Payout through AnyMoney

---

lib/payment_services/any_money/payout_adapter.rb

Fix https://github.com/alfagen/kassa-admin/issues/695

Fix AnyMoney status updater

---

lib/payment_services/crypto_apis/invoice.rb
lib/payment_services/crypto_apis/payout.rb

Related to https://github.com/alfagen/kassa-admin/pull/693

Cryptoapis service: returns transaction hash

---

lib/payment_services/any_money/invoicer.rb

Fix https://github.com/alfagen/kassa-admin/issues/703

Use comission of PM setting

---

lib/payment_services/payeer.rb
lib/payment_services/payeer/client.rb
lib/payment_services/payeer/payout.rb
lib/payment_services/payeer/payout_adapter.rb

Related to https://github.com/alfagen/kassa-admin/pull/749

Payeer: payout adapter

---

lib/payment_services/adv_cash.rb
lib/payment_services/adv_cash/client.rb
lib/payment_services/adv_cash/payout.rb
lib/payment_services/adv_cash/payout_adapter.rb

Related to https://github.com/alfagen/kassa-admin/pull/750

Выплаты AdvCASH

---

lib/payment_services/perfect_money/client.rb

Фикс: https://app.bugsnag.com/alfa-genesis/kassa-dot-cc-1/errors/60ae572eba2d7f000709dd6e?filters[event.since][0]=30d&filters[error.status][0]=open

Perfect Money выплаты: фикс ошибки

---

lib/payment_services/obmenka.rb
lib/payment_services/obmenka/client.rb
lib/payment_services/obmenka/payout.rb
lib/payment_services/obmenka/payout_adapter.rb

Related to https://github.com/alfagen/kassa-admin/pull/765

Шлюз Obmenka: выплаты

---

lib/payment_services/crypto_apis/payout_clients/dash_client.rb

Cryptoapis/Dash: Fix payouts

---

lib/payment_services/adv_cash/invoicer.rb
lib/payment_services/ali_kassa/invoicer.rb
lib/payment_services/ali_kassa_peer_to_peer/invoicer.rb
lib/payment_services/any_money/invoicer.rb
lib/payment_services/perfect_money/invoicer.rb

Related to https://github.com/alfagen/kassa-admin/pull/713

Use redirect_url of PS

---

lib/payment_services/adv_cash/invoicer.rb
lib/payment_services/ali_kassa/invoicer.rb
lib/payment_services/ali_kassa_peer_to_peer/invoicer.rb
lib/payment_services/any_money/invoicer.rb
lib/payment_services/perfect_money/invoicer.rb

Related to https://github.com/alfagen/kassa-admin/pull/799
Затестил на стейдже - заявки с  Perfect Money теперь создаються: ![](http://joxi.ru/nAyvvGxUajwaqr.jpg)

Fix: Orders redirect_url reference

---

lib/payment_services/crypto_apis/payout.rb

https://github.com/alfagen/kassa-admin/pull/830

ETH/ETC: fix fee calculation

---

lib/payment_services/crypto_apis/payout.rb
lib/payment_services/crypto_apis/payout_adapter.rb

https://github.com/alfagen/kassa-admin/pull/836

Cryproapis: fix fee calculation

---

lib/payment_services/crypto_apis/invoice.rb
lib/payment_services/crypto_apis/invoicer.rb

https://github.com/alfagen/kassa-admin/issues/812

Cryptoapis: делать резерв если касса нашла транзакцию

---

lib/payment_services/base/payout_adapter.rb
lib/payment_services/crypto_apis/payout_adapter.rb

https://github.com/alfagen/kassa-admin/issues/767

Управление комиссиями

---

lib/payment_services/liquid/payout_adapter.rb

https://github.com/alfagen/kassa-admin/issues/781

Комиссии Ликвид

---

lib/payment_services/crypto_apis/invoice.rb

https://github.com/alfagen/kassa-admin/issues/828

Cryptoapis LTC: 1 confirmation to confirm invoice

---

lib/payment_services/exmo/invoicer.rb
lib/payment_services/exmo/payout.rb
lib/payment_services/exmo/payout_adapter.rb

https://github.com/alfagen/kassa-admin/pull/889

Выплаты с Exmo: добавляем invoice параметр

---

lib/payment_services/binance.rb
lib/payment_services/binance/client.rb
lib/payment_services/binance/invoice.rb
lib/payment_services/binance/invoicer.rb
lib/payment_services/binance/payout.rb
lib/payment_services/binance/payout_adapter.rb

https://github.com/alfagen/kassa-admin/pull/894

Binance: выплаты

---

lib/payment_services/adv_cash/invoicer.rb
lib/payment_services/ali_kassa/invoicer.rb
lib/payment_services/ali_kassa_peer_to_peer/invoicer.rb
lib/payment_services/any_money/invoicer.rb
lib/payment_services/kuna/invoicer.rb
lib/payment_services/obmenka/invoicer.rb
lib/payment_services/perfect_money/invoicer.rb
lib/payment_services/qiwi/invoicer.rb

https://github.com/alfagen/kassa-admin/pull/897

Kuna/Obmenka: add redirect url

---

lib/payment_services/exmo/payout.rb
lib/payment_services/exmo/payout_adapter.rb

https://github.com/alfagen/kassa-admin/pull/904

Exmo NEM: фикс выплат

---

lib/payment_services/binance/payout.rb
lib/payment_services/binance/payout_adapter.rb

https://github.com/alfagen/kassa-admin/pull/909

Binance: улучшения выплат

---

lib/payment_services/crypto_apis/invoicer.rb

https://github.com/alfagen/kassa-admin/pull/966

Cryptoapis: match transactions with delta

---

lib/payment_services/exmo/payout_adapter.rb

https://github.com/alfagen/kassa-admin/issues/991

Exmo: use integer amount for NEO currency

---

lib/payment_services.rb
lib/payment_services/master_processing.rb
lib/payment_services/master_processing/client.rb
lib/payment_services/master_processing/invoice.rb
lib/payment_services/master_processing/invoicer.rb

Новый эквайринг, http://mpcvip.ru/api_doc/?go#476f380340

MasterProcessing payway: Invoicer

---

lib/payment_services/crypto_apis_v2/blockchain.rb
lib/payment_services/crypto_apis_v2/client.rb

https://github.com/alfagen/kassa-admin/issues/1010

Use standart fee for zcach; slow for bitcoin

---

lib/payment_services/adv_cash/payout_adapter.rb
lib/payment_services/any_money/payout_adapter.rb
lib/payment_services/appex_money/payout_adapter.rb
lib/payment_services/binance/payout_adapter.rb
lib/payment_services/block_io/payout_adapter.rb
lib/payment_services/crypto_apis/payout_adapter.rb
lib/payment_services/crypto_apis/payout_clients/base_client.rb
lib/payment_services/crypto_apis/payout_clients/ethereum_client.rb
lib/payment_services/crypto_apis/payout_clients/omni_client.rb
lib/payment_services/crypto_apis_v2/client.rb
lib/payment_services/crypto_apis_v2/payout_adapter.rb
lib/payment_services/exmo/invoicer.rb
lib/payment_services/exmo/payout_adapter.rb
lib/payment_services/kuna/payout_adapter.rb
lib/payment_services/liquid/payout_adapter.rb
lib/payment_services/master_processing/payout_adapter.rb
lib/payment_services/obmenka/payout_adapter.rb
lib/payment_services/payeer/payout_adapter.rb
lib/payment_services/perfect_money/payout_adapter.rb
lib/payment_services/qiwi/payout_adapter.rb

https://github.com/alfagen/kassa-admin/pull/1019

Use outcome_api_key/secret for payout adapters

---

lib/payment_services/block_io.rb
lib/payment_services/block_io/client.rb
lib/payment_services/block_io/invoice.rb
lib/payment_services/block_io/invoicer.rb
lib/payment_services/block_io/payout.rb
lib/payment_services/block_io/payout_adapter.rb
lib/payment_services/block_io/transaction.rb

Добавить `Invoicer` для BlockIO шлюза.
Чтобы была возможность получать оплату через этот шлюз.
https://github.com/alfagen/kassa-admin/pull/1024

BlockIO: Invoicer

---

lib/payment_services/blockchair/invoicer.rb
lib/payment_services/crypto_apis_v2/invoicer.rb

https://app.bugsnag.com/alfa-genesis/kassa-dot-cc-1/errors/62242f5aba0cd5000ac51b82?filters[event.since]=30d&filters[error.status]=open

Fix bugsnap errors

---

lib/payment_services/block_io/payout_adapter.rb

Добавляем возможность приема/выплат криптовалюты Doge через шлюз BlockIO.
Чтобы была такая возможность :)
На стейдже все успешно завелось.

BlockIO: invoicer/payout: add dogecoin

---

lib/payment_services/crypto_apis_v2/blockchain.rb
lib/payment_services/crypto_apis_v2/client.rb

- XRP: шифровать адрес, если указан тег
- Добавить USDT TRC-20

Cryptoapis правки

---

lib/payment_services/master_processing/client.rb
lib/payment_services/master_processing/invoicer.rb
lib/payment_services/master_processing/response.rb

https://github.com/alfagen/kassa-admin/issues/1109
Подключим новый способ оплаты - MasterProcessingH2H
Документация - https://mpcvip.ru/api_doc/#h2h

MasterProcessing invoicer: add h2h

---

lib/payment_services/binance/invoice.rb
lib/payment_services/binance/invoicer.rb
lib/payment_services/binance/payout.rb
lib/payment_services/binance/payout_adapter.rb
lib/payment_services/crypto_apis_v2/blockchain.rb
lib/payment_services/crypto_apis_v2/client.rb
lib/payment_services/crypto_apis_v2/invoice.rb
lib/payment_services/crypto_apis_v2/invoicer.rb
lib/payment_services/crypto_apis_v2/payout_adapter.rb
lib/payment_services/crypto_apis_v2/transaction.rb
lib/payment_services/crypto_apis_v2/transaction_matcher.rb
lib/payment_services/crypto_apis_v2/transaction_repository.rb
lib/payment_services/exmo/payout.rb
lib/payment_services/exmo/payout_adapter.rb

Cryptoapis V2: фикс багов/рефакторинг

---

lib/payment_services/oko_otc/client.rb
lib/payment_services/oko_otc/payout_adapter.rb

https://github.com/alfagen/kassa-admin/issues/1203

Обновление шлюза OTC

---

README.md
lib/payment_services.rb
lib/payment_services/rbk.rb
lib/payment_services/rbk/client.rb
lib/payment_services/rbk/customer.rb
lib/payment_services/rbk/customer_client.rb
lib/payment_services/rbk/identity.rb
lib/payment_services/rbk/identity_client.rb
lib/payment_services/rbk/invoice.rb
lib/payment_services/rbk/invoice_client.rb
lib/payment_services/rbk/invoicer.rb
lib/payment_services/rbk/payment.rb
lib/payment_services/rbk/payment_card.rb
lib/payment_services/rbk/payment_client.rb
lib/payment_services/rbk/payout.rb
lib/payment_services/rbk/payout_adapter.rb
lib/payment_services/rbk/payout_client.rb
lib/payment_services/rbk/payout_destination.rb
lib/payment_services/rbk/payout_destination_client.rb
lib/payment_services/rbk/wallet.rb
lib/payment_services/rbk/wallet_client.rb

Обновление до Rails 6
Чтобы поддержать обновление в основном репозитории

Обновление до Rails 6

---

lib/payment_services/any_pay.rb
lib/payment_services/any_pay/client.rb
lib/payment_services/any_pay/payout.rb
lib/payment_services/any_pay/payout_adapter.rb

[Дока](https://anypay.io/doc/api/create-payout)

Выплаты QIWI через шлюз AnyPay

---

lib/payment_services.rb
lib/payment_services/base.rb
lib/payment_services/base/crypto_payout.rb
lib/payment_services/one_crypto.rb
lib/payment_services/one_crypto/client.rb
lib/payment_services/one_crypto/invoice.rb
lib/payment_services/one_crypto/payout.rb
lib/payment_services/one_crypto/payout_adapter.rb
lib/payment_services/one_crypto/transaction.rb

[Дока](https://docs.onecrypto.pro/#create-withdraw-transaction-2)

Выплата крипты через OneCrypto

---

lib/payment_services/ex_pay/invoicer.rb
lib/payment_services/ex_pay/payout_adapter.rb

https://github.com/alfagen/kassa-admin/issues/1270

Доработки по ExPay

---

lib/payment_services.rb
lib/payment_services/base.rb
lib/payment_services/base/p2p_bank_resolver.rb
lib/payment_services/base/payout_adapter.rb
lib/payment_services/ex_pay/invoicer.rb
lib/payment_services/pay_for_u_h2h/invoicer.rb
lib/payment_services/paylama/currency_repository.rb
lib/payment_services/paylama_p2p/invoicer.rb

У нас на проде есть отдельные рублевые платежки: СберOnline и Tinkoff. Нужно добавить новую настройку ПС: `Название банка для p2p`
Чтобы не было случаев, когда пользователь меняет Tinkoff -> Any, а ему показывает карту для оплаты от Сбербанка.

Доработки по P2P

---

lib/payment_services/cryptomus/client.rb
lib/payment_services/cryptomus/invoice.rb
lib/payment_services/cryptomus/invoicer.rb
lib/payment_services/cryptomus/payout_adapter.rb

https://github.com/alfagen/kassa-admin/issues/1415
https://github.com/alfagen/kassa-admin/issues/1416

Cryptomus: комиссия и перерасчет
